Repository lerna/lerna-changelog, pull requests merged in 2019-11, with the labels that each got.

#159 Adjust `.npmignore` file
  .npmignore
Labels: internal

#160 Drop support for Node 6
  .travis.yml
  package.json
Labels: breaking

#158 Upgrade `yargs` to v13
  package.json
  yarn.lock
Labels: enhancement

#161 CI: Add Node.js 12 to the test matrix
  .travis.yml
Labels: internal

#147 Switch from TSLint to ESLint
  .eslintrc.js
  package.json
  yarn.lock
Labels: internal

#140 Set TypeScript `target` to `es2015`
  tsconfig.json
Labels: internal

#153 enhancement: Update string renderer to add empty lines only when commits are present.
  src/functional/__snapshots__/markdown-empty.spec.ts.snap
  src/functional/markdown-empty.spec.ts
  src/markdown-renderer.ts
Labels: enhancement
