Repository lerna/lerna-changelog, pull requests merged in 2021-08, with the labels that each got.

#469 Replace TravisCI with GitHub Actions
  .github/workflows/ci.yml
  .travis.yml
Labels: internal

#472 README: Recommend `npx` usage instead of global install
  README.md
Labels: documentation

#473 Use `pnpm` instead of `yarn` for development
  .github/workflows/ci.yml
  pnpm-lock.yaml
  yarn.lock
Labels: internal

#474 Remove obsolete TSLint references
  .npmignore
  src/cli.ts
  src/find-pull-request-id.spec.ts
  src/functional/markdown-empty.spec.ts
  src/functional/markdown-full.spec.ts
  tslint.json
Labels: internal

#475 git: Extract `getRootPath()` function
  src/configuration.ts
  src/git.ts
Labels: internal

#486 Drop support for Node.js 10
  .github/workflows/ci.yml
  package.json
Labels: breaking

#487 CI: Update `pnpm` version
  .github/workflows/ci.yml
Labels: internal

#488 Disable dependabot
  .github/dependabot.yml
Labels: internal

#489 Update `.npmignore` file
  .npmignore
Labels: internal

#490 CI: Release tags automatically
  .github/workflows/release.yml
  package.json
Labels: internal

#491 Add `release-it` to simplify the release process
  .release-it.js
  package.json
  pnpm-lock.yaml
Labels: internal

#492 Add `dependabot-preview` to default list of ignored committers
  src/configuration.ts
Labels: enhancement

#493 CI: Run `pnpm install` before `npm publish`
  .github/workflows/release.yml
Labels: internal

#494 Update yargs to v17.x
  package.json
  pnpm-lock.yaml
Labels: internal

#398 Fix handling of --next-version-from-metadata option
  src/cli.ts
Labels: bug

#296 Omit commiters line when all are filtered out
  src/__snapshots__/markdown-renderer.spec.ts.snap
  src/markdown-renderer.spec.ts
  src/markdown-renderer.ts
Labels: bug

#495 Add support for `--repo` option
  src/cli.ts
  src/configuration.spec.ts
  src/configuration.ts
Labels: enhancement
